trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  system.debug: true

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Ensure artifact staging directory exists
- task: Bash@3
  displayName: 'Ensure artifact staging directory exists'
  inputs:
    targetType: 'inline'
    script: |
      mkdir -p "$(Build.ArtifactStagingDirectory)"

# Run analysis task
- task: runAnalysisTask@0
  displayName: 'Run Analysis Task'
  inputs:
    projectName: 'Bubber Dinner API'
    sourceDirectory: '$(Build.SourcesDirectory)'
    outputFilePath: '$(Build.ArtifactStagingDirectory)/technical-documentation.json'

# Validate output file
- task: Bash@3
  displayName: 'Check if output file exists'
  inputs:
    targetType: 'inline'
    script: |
      if [ -f "$(Build.ArtifactStagingDirectory)/technical-documentation.json" ]; then
        echo "Output file exists."
      else
        echo "Output file does not exist."
        exit 1
      fi

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
