@host=https://localhost:7262

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKT0hOQ0VOQSIsImdpdmVuX25hbWUiOiJKT0hOIiwiZmFtaWx5X25hbWUiOiJDRU5BIiwianRpIjoiNWEyYmY1ZTYtNTlkYy00MTI2LWFmMDUtZjE3Yjc5NzQzY2I3IiwiZXhwIjoxNzAzOTQyNjE5LCJpc3MiOiJCdWJiZXJEaW5uZXIuU2VydmljZXMiLCJhdWQiOiJCdWJiZXJEaW5uZXIuQ2xpZW50In0.oRG8s95ZNj4U9WI3-gqBcLcceZ3joN0OVowI_g59BoE